{
 "title": "Hasura Example Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Health Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "hasura_healthy{}" }
   ]
  },
  {
   "title": "Metadata consistent",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "hasura_metadata_consistency_status{}"
    }
   ]
  },
  {
   "title": "Requests/sec",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(hasura_request_query_counter{}[1m]))"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(hasura_request_query_counter{error=\"\"}[1m])) / sum(rate(hasura_request_query_counter{}[1m]))"
    }
   ]
  },
  {
   "title": "Average Query Execution Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(hasura_query_execution_seconds_sum{}[$__interval])) / sum(rate(hasura_query_execution_seconds_count{}[$__interval]))"
    }
   ]
  },
  {
   "title": "Websockets Open",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 10 },
   "targets": [
    { "expr": "hasura_websockets_active{}" }
   ]
  },
  {
   "title": "Active Subscriptions",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 10 },
   "targets": [
    {
     "expr": "hasura_websockets_operations_active{}"
    }
   ]
  },
  {
   "title": "Request Rates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hasura_request_query_counter{}[$__interval]))",
     "legendFormat": "Success Requests"
    },
    {
     "expr": "sum(rate(hasura_request_query_counter{error!=\"\"}[$__interval]))",
     "legendFormat": "Error Requests"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Success Request Rates by Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hasura_request_query_counter{error=\"\"}[$__interval])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Average Query execution by operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hasura_query_execution_seconds_sum{}[$__interval])) by (operation) / sum(rate(hasura_query_execution_seconds_count{}[$__interval])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}